edition = "2024"
error_on_line_overflow = true
error_on_unformatted = true
max_width = 100
overflow_delimited_expr = false
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_try_shorthand = true